### ISSUE TITLE
Drafts vs 9999 version?

### ISSUE THREAD

**Issue by oxr463** [TheChymera/overlay#40]
Could you please explain the reasoning behind using a `drafts` directory? I am genuinely curious as to your workflow for this.

**Comment by TheChymera** [comment]
That is a directory for ebuilds which are not used and workable yet. They're not -9999 generally, but versioned ebuilds the issues with which are still too significantly broken to qualify (imho) even for hard-masked listings. The way I see it hard masked means “this will probably not work, but you can try”. Drafts means “this will in no case works, and you're probably better off writing a new ebuild than trying to decode my work in progress”.

**Comment by oxr463** [comment]
Oh I see. Thanks for the information!
